// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel cs_main

struct some_data
{
    float3 position;
    float4 color;
};

RWStructuredBuffer<some_data> return_data;
float resolution;

[numthreads(10,1,1)]
void cs_main (uint3 id : SV_DispatchThreadID)
{
    float posX = id.x / resolution;
    some_data data = return_data[id.x];
    data.color = float4(posX, 0.0, 0.0, 1.0);

    data.position = float3(0.0, 0.0, 0.0);

    return_data[id.x] = data;
}
